import Head from 'next/head'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Spotify 2.0 (Clone)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1> Spotify-2.0.clone()</h1>

      <main>
        {/*   Sidebar    */}
        {/*   Center    */}
      </main>

      <div> {/*   Player    */} </div>
    </div>
  )
}
